/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author USUARIO
 */
public class ActualizarContacto extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarContacto
     */
    public ActualizarContacto() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoBase = new javax.swing.JPanel();
        panelFondoTitulo = new javax.swing.JPanel();
        labTituloDeInterfaz = new javax.swing.JLabel();
        labNombreBuscar = new javax.swing.JLabel();
        txtNombreBuscar = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        labNombreAct = new javax.swing.JLabel();
        labTelefonoAct = new javax.swing.JLabel();
        labDireccAct = new javax.swing.JLabel();
        labCorreoAct = new javax.swing.JLabel();
        txtNombreActualizar = new javax.swing.JTextField();
        txtTelefonoAct = new javax.swing.JTextField();
        txtDireccionAct = new javax.swing.JTextField();
        txtCorreoAct = new javax.swing.JTextField();
        btActualizarContacto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondoBase.setBackground(new java.awt.Color(255, 204, 204));

        panelFondoTitulo.setBackground(new java.awt.Color(255, 255, 255));

        labTituloDeInterfaz.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labTituloDeInterfaz.setForeground(new java.awt.Color(51, 51, 0));
        labTituloDeInterfaz.setText("Actualizar Datos de contacto");

        javax.swing.GroupLayout panelFondoTituloLayout = new javax.swing.GroupLayout(panelFondoTitulo);
        panelFondoTitulo.setLayout(panelFondoTituloLayout);
        panelFondoTituloLayout.setHorizontalGroup(
            panelFondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTituloDeInterfaz)
                .addGap(163, 163, 163))
        );
        panelFondoTituloLayout.setVerticalGroup(
            panelFondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoTituloLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labTituloDeInterfaz)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        labNombreBuscar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labNombreBuscar.setForeground(new java.awt.Color(0, 0, 0));
        labNombreBuscar.setText("Nombre del Contacto : ");

        txtNombreBuscar.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreBuscar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNombreBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBuscarActionPerformed(evt);
            }
        });

        btBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Downloads\\lupa (1).png")); // NOI18N
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        labNombreAct.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labNombreAct.setForeground(new java.awt.Color(0, 0, 0));
        labNombreAct.setText("Nombre :");

        labTelefonoAct.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labTelefonoAct.setForeground(new java.awt.Color(0, 0, 0));
        labTelefonoAct.setText("Telefono :");

        labDireccAct.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labDireccAct.setForeground(new java.awt.Color(0, 0, 0));
        labDireccAct.setText("Direccion :");

        labCorreoAct.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labCorreoAct.setForeground(new java.awt.Color(0, 0, 0));
        labCorreoAct.setText("Correo :");

        txtNombreActualizar.setBackground(new java.awt.Color(204, 204, 204));
        txtNombreActualizar.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtNombreActualizar.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActualizarActionPerformed(evt);
            }
        });

        txtTelefonoAct.setBackground(new java.awt.Color(204, 204, 204));
        txtTelefonoAct.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtTelefonoAct.setForeground(new java.awt.Color(0, 0, 0));

        txtDireccionAct.setBackground(new java.awt.Color(204, 204, 204));
        txtDireccionAct.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtDireccionAct.setForeground(new java.awt.Color(0, 0, 0));

        txtCorreoAct.setBackground(new java.awt.Color(204, 204, 204));
        txtCorreoAct.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        txtCorreoAct.setForeground(new java.awt.Color(0, 0, 0));

        btActualizarContacto.setBackground(new java.awt.Color(204, 204, 204));
        btActualizarContacto.setForeground(new java.awt.Color(0, 153, 153));
        btActualizarContacto.setText("Actualizar");
        btActualizarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoBaseLayout = new javax.swing.GroupLayout(panelFondoBase);
        panelFondoBase.setLayout(panelFondoBaseLayout);
        panelFondoBaseLayout.setHorizontalGroup(
            panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFondoBaseLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labNombreBuscar)
                .addGap(18, 18, 18)
                .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(panelFondoBaseLayout.createSequentialGroup()
                .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoBaseLayout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNombreAct)
                            .addComponent(labTelefonoAct)
                            .addComponent(labDireccAct)
                            .addComponent(labCorreoAct))
                        .addGap(125, 125, 125)
                        .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreActualizar)
                            .addComponent(txtTelefonoAct)
                            .addComponent(txtDireccionAct)
                            .addComponent(txtCorreoAct, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(panelFondoBaseLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(btActualizarContacto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoBaseLayout.setVerticalGroup(
            panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBaseLayout.createSequentialGroup()
                .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFondoBaseLayout.createSequentialGroup()
                        .addComponent(panelFondoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labNombreBuscar)
                                .addComponent(txtNombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(62, 62, 62)
                        .addComponent(labNombreAct))
                    .addComponent(txtNombreActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTelefonoAct)
                    .addComponent(txtTelefonoAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDireccAct)
                    .addComponent(txtDireccionAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFondoBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCorreoAct)
                    .addComponent(txtCorreoAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btActualizarContacto)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Eventos y métodos para interactuar con la interfaz de usuario
    
    private void txtNombreBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBuscarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String nombreBuscar = txtNombreBuscar.getText();

    // Realizar la búsqueda en la base de datos
    List<String> contactosEncontrados = buscarContactosPorNombre(nombreBuscar);

    if (contactosEncontrados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No se encontraron contactos con ese nombre.");
    } else {
        // contactos encontrados
        String[] contactosArray = contactosEncontrados.toArray(new String[0]);
        

        // Crear una lista desplegable con los contactos encontrados
        JComboBox<String> contactosComboBox = new JComboBox<>(contactosArray);
        

        
        JPanel panel = new JPanel();
        panel.add(contactosComboBox);

        // Mostrar una ventana emergente con la lista desplegable
        JFrame frame = new JFrame();
        int result = JOptionPane.showConfirmDialog(null, panel, "Seleccione un contacto", JOptionPane.OK_CANCEL_OPTION);

        if (result == JOptionPane.OK_OPTION) {
            // El usuario seleccionó un contacto
            String contactoSeleccionado = (String) contactosComboBox.getSelectedItem();
            //mostrar los datos del susodicho para ver que cambios realizar
            String [] detalleContact = contactoSeleccionado.split("-");
            txtNombreActualizar.setText(detalleContact[0]);
            txtTelefonoAct.setText(detalleContact[1]);
            txtDireccionAct.setText(detalleContact[2]);
            txtCorreoAct.setText(detalleContact[3]);
            
         
        }
    }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void txtNombreActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActualizarActionPerformed

    private void btActualizarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarContactoActionPerformed
        String nuevoNombre = txtNombreActualizar.getText();
        String nuevoTelefono = txtTelefonoAct.getText();
        String nuevaDireccion = txtDireccionAct.getText();
        String nuevoCorreo = txtCorreoAct.getText();

        // Realizar la actualización en la base de datos para el contacto seleccionado
        actualizarContactoSeleccionado(nuevoNombre, nuevoTelefono, nuevaDireccion, nuevoCorreo);

        // Limpiar los campos de texto
        txtNombreActualizar.setText("");
        txtTelefonoAct.setText("");
        txtDireccionAct.setText("");
        txtCorreoAct.setText("");

        JOptionPane.showMessageDialog(this, "Contacto actualizado con éxito.");
    }//GEN-LAST:event_btActualizarContactoActionPerformed
    
    private List<String> buscarContactosPorNombre(String nombre) {
        List<String> contactosEncontrados = new ArrayList<>();

    // Consulta SQL para buscar contactos por nombre
    String sql = "SELECT * FROM contactos WHERE nombre = ?";

    try (Connection connection = ConnectionDB.getConnectionBD();
         PreparedStatement statement = connection.prepareStatement(sql)) {
        statement.setString(1, nombre); // Establecer el valor del parámetro en la consulta SQL no borre

        try (ResultSet resultSet = statement.executeQuery()) {
            // Recorrer los resultados y agregarlos a la lista
            while (resultSet.next()) {
                String nombreContacto = resultSet.getString("nombre");
                String telefonoContacto = resultSet.getString("numero_telefono");
                String direccionContacto = resultSet.getString("direccion");
                String correoContacto = resultSet.getString("correo");

                //  cadena con los datos del contacto y agregarla a la lista
                String contacto = nombreContacto + " - " + telefonoContacto + " - " + direccionContacto + " - " + correoContacto;
                contactosEncontrados.add(contacto);
            }
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al buscar contactos: " + e.getMessage());
    }

    return contactosEncontrados;
    }

    private void actualizarContactoSeleccionado(String nuevoNombre, String nuevoTelefono, String nuevaDireccion, String nuevoCorreo) {
         // Consulta SQL para actualizar el contacto
    String sql = "UPDATE contactos SET nombre = ?, numero_telefono = ?, direccion = ?, correo = ? WHERE nombre = ?";

    try (Connection connection = ConnectionDB.getConnectionBD();
         PreparedStatement statement = connection.prepareStatement(sql)) {
        statement.setString(1, nuevoNombre);
        statement.setString(2, nuevoTelefono);
        statement.setString(3, nuevaDireccion);
        statement.setString(4, nuevoCorreo);
        statement.setString(5, txtNombreBuscar.getText()); // Usamos el nombre anterior como criterio de actualización

        int rowsAffected = statement.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Contacto actualizado con éxito.");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró ningún contacto para actualizar.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al actualizar el contacto: " + e.getMessage());
    }
    }

    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizarContacto;
    private javax.swing.JButton btBuscar;
    private javax.swing.JLabel labCorreoAct;
    private javax.swing.JLabel labDireccAct;
    private javax.swing.JLabel labNombreAct;
    private javax.swing.JLabel labNombreBuscar;
    private javax.swing.JLabel labTelefonoAct;
    private javax.swing.JLabel labTituloDeInterfaz;
    private javax.swing.JPanel panelFondoBase;
    private javax.swing.JPanel panelFondoTitulo;
    private javax.swing.JTextField txtCorreoAct;
    private javax.swing.JTextField txtDireccionAct;
    private javax.swing.JTextField txtNombreActualizar;
    private javax.swing.JTextField txtNombreBuscar;
    private javax.swing.JTextField txtTelefonoAct;
    // End of variables declaration//GEN-END:variables
}
