/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto;
/*
 * Importación de paquetes y clases necesarias.
 */
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * * Clase Agregar que representa la ventana para agregar contactos.

 * @author USUARIO
 */
public class Agregar extends javax.swing.JFrame {

    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labNombre = new javax.swing.JLabel();
        labTelefono = new javax.swing.JLabel();
        labDireccion = new javax.swing.JLabel();
        labCorreo = new javax.swing.JLabel();
        txtIngNombre = new javax.swing.JTextField();
        txtIngTelefono = new javax.swing.JTextField();
        txtIngDireccion = new javax.swing.JTextField();
        txtIngCorreo = new javax.swing.JTextField();
        btAgregarContacto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        labNombre.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labNombre.setForeground(new java.awt.Color(0, 0, 0));
        labNombre.setText("Ingresar Nombre :");

        labTelefono.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labTelefono.setForeground(new java.awt.Color(0, 0, 0));
        labTelefono.setText("Ingresar Telefono : ");

        labDireccion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labDireccion.setForeground(new java.awt.Color(0, 0, 0));
        labDireccion.setText("Ingresar Direccion :");

        labCorreo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labCorreo.setForeground(new java.awt.Color(0, 0, 0));
        labCorreo.setText("Ingresar Correo :");

        txtIngNombre.setBackground(new java.awt.Color(204, 204, 204));
        txtIngNombre.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtIngNombre.setForeground(new java.awt.Color(0, 0, 0));

        txtIngTelefono.setBackground(new java.awt.Color(204, 204, 204));
        txtIngTelefono.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtIngTelefono.setForeground(new java.awt.Color(0, 0, 0));

        txtIngDireccion.setBackground(new java.awt.Color(204, 204, 204));
        txtIngDireccion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtIngDireccion.setForeground(new java.awt.Color(0, 0, 0));

        txtIngCorreo.setBackground(new java.awt.Color(204, 204, 204));
        txtIngCorreo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtIngCorreo.setForeground(new java.awt.Color(0, 0, 0));

        btAgregarContacto.setBackground(new java.awt.Color(255, 255, 255));
        btAgregarContacto.setForeground(new java.awt.Color(0, 204, 204));
        btAgregarContacto.setText("Agregar");
        btAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labNombre)
                    .addComponent(labTelefono)
                    .addComponent(labDireccion)
                    .addComponent(labCorreo))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIngNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(txtIngTelefono)
                    .addComponent(txtIngDireccion)
                    .addComponent(txtIngCorreo))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(btAgregarContacto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labNombre)
                    .addComponent(txtIngNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTelefono)
                    .addComponent(txtIngTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDireccion)
                    .addComponent(txtIngDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCorreo)
                    .addComponent(txtIngCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btAgregarContacto)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarContactoActionPerformed
        String nombreUser = txtIngNombre.getText();
    String telefonoUser = txtIngTelefono.getText();
    String direccUser = txtIngDireccion.getText();
    String correoUser = txtIngCorreo.getText();

    if (nombreUser.isEmpty() || telefonoUser.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese los datos básicos de la persona (nombre, teléfono).");
    } else {
        // Realizar la inserción en la base de datos
        Connection connection = ConnectionDB.getConnectionBD();
        
        if (connection != null) {
            try {
                // Crear una sentencia  para la inserción
                String sql = "INSERT INTO contactos (nombre, numero_telefono, direccion, correo) VALUES (?, ?, ?, ?)";
                java.sql.PreparedStatement statement = connection.prepareStatement(sql);
                statement.setString(1, nombreUser);
                statement.setString(2, telefonoUser);
                statement.setString(3, direccUser);
                statement.setString(4, correoUser);
                
                // Ejecutar la inserción
                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(this, "Contacto Agregado con éxito.");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al agregar el contacto.");
                }
                
                // Cerrar la conexión y liberar espacio?
                statement.close();
                connection.close();
                this.dispose(); // Cierra la ventana "Agregar" no la borre estupido 

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error en la inserción: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo conectar a la base de datos.");
        }
    }
    
    }//GEN-LAST:event_btAgregarContactoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarContacto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labCorreo;
    private javax.swing.JLabel labDireccion;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labTelefono;
    private javax.swing.JTextField txtIngCorreo;
    private javax.swing.JTextField txtIngDireccion;
    private javax.swing.JTextField txtIngNombre;
    private javax.swing.JTextField txtIngTelefono;
    // End of variables declaration//GEN-END:variables
}
