/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/*
 * Importación de paquetes y clases necesarias.
 */
package agenda;
import agenda.ListaContactos;
import agenda.EliminarContacto;
import agenda.Agregar;
import agenda.ActualizarContacto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JTextArea;


/**
 * Clase Principal que representa la ventana principal de la aplicación.
 */
public class Principal extends javax.swing.JFrame {

    
    public Principal(String textoNomb) {
        initComponents();
        mostrarFechaActual();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Bienvenido "+textoNomb);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panleFondoUlt = new javax.swing.JPanel();
        panelFondoSup = new javax.swing.JPanel();
        labTituloMomento = new javax.swing.JLabel();
        labfecha = new javax.swing.JLabel();
        labImagenIcon = new javax.swing.JLabel();
        panelFondoOpciones = new javax.swing.JPanel();
        btAgregarContacto = new javax.swing.JButton();
        btMostrarListaCont = new javax.swing.JButton();
        btActualizarContac = new javax.swing.JButton();
        btEliminarContac = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panleFondoUlt.setBackground(new java.awt.Color(255, 255, 255));

        panelFondoSup.setBackground(new java.awt.Color(102, 255, 255));
        panelFondoSup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labTituloMomento.setBackground(new java.awt.Color(0, 0, 0));
        labTituloMomento.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        labTituloMomento.setForeground(new java.awt.Color(0, 0, 0));
        labTituloMomento.setText("Bienvenido!");

        labfecha.setBackground(new java.awt.Color(0, 0, 0));
        labfecha.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labfecha.setForeground(new java.awt.Color(0, 0, 0));
        labfecha.setText("11/10/2023");

        javax.swing.GroupLayout panelFondoSupLayout = new javax.swing.GroupLayout(panelFondoSup);
        panelFondoSup.setLayout(panelFondoSupLayout);
        panelFondoSupLayout.setHorizontalGroup(
            panelFondoSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoSupLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labImagenIcon)
                .addGap(286, 286, 286)
                .addComponent(labTituloMomento, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(211, 211, 211)
                .addComponent(labfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        panelFondoSupLayout.setVerticalGroup(
            panelFondoSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoSupLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelFondoSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labImagenIcon)
                    .addGroup(panelFondoSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labfecha)
                        .addComponent(labTituloMomento)))
                .addGap(32, 32, 32))
        );

        panelFondoOpciones.setBackground(new java.awt.Color(102, 255, 255));

        btAgregarContacto.setBackground(new java.awt.Color(255, 255, 255));
        btAgregarContacto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btAgregarContacto.setForeground(new java.awt.Color(0, 0, 0));
        btAgregarContacto.setText("Agregar Contacto");
        btAgregarContacto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btAgregarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarContactoActionPerformed(evt);
            }
        });

        btMostrarListaCont.setBackground(new java.awt.Color(255, 255, 255));
        btMostrarListaCont.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btMostrarListaCont.setForeground(new java.awt.Color(0, 0, 0));
        btMostrarListaCont.setText("Lista de Contactos");
        btMostrarListaCont.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btMostrarListaCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMostrarListaContActionPerformed(evt);
            }
        });

        btActualizarContac.setBackground(new java.awt.Color(255, 255, 255));
        btActualizarContac.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btActualizarContac.setForeground(new java.awt.Color(0, 0, 0));
        btActualizarContac.setText("Actualizar Contacto");
        btActualizarContac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btActualizarContac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarContacActionPerformed(evt);
            }
        });

        btEliminarContac.setBackground(new java.awt.Color(255, 255, 255));
        btEliminarContac.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btEliminarContac.setForeground(new java.awt.Color(0, 0, 0));
        btEliminarContac.setText("Eliminar Contacto");
        btEliminarContac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btEliminarContac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarContacActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Salir");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoOpcionesLayout = new javax.swing.GroupLayout(panelFondoOpciones);
        panelFondoOpciones.setLayout(panelFondoOpcionesLayout);
        panelFondoOpcionesLayout.setHorizontalGroup(
            panelFondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btAgregarContacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btMostrarListaCont, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btActualizarContac, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
            .addComponent(btEliminarContac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoOpcionesLayout.setVerticalGroup(
            panelFondoOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoOpcionesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btAgregarContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btMostrarListaCont, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btActualizarContac, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btEliminarContac, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panleFondoUltLayout = new javax.swing.GroupLayout(panleFondoUlt);
        panleFondoUlt.setLayout(panleFondoUltLayout);
        panleFondoUltLayout.setHorizontalGroup(
            panleFondoUltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panleFondoUltLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panleFondoUltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFondoSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panleFondoUltLayout.createSequentialGroup()
                        .addComponent(panelFondoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panleFondoUltLayout.setVerticalGroup(
            panleFondoUltLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panleFondoUltLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelFondoSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(panelFondoOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFondoUlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panleFondoUlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btAgregarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarContactoActionPerformed
        Agregar ventanaAgregar = new Agregar();
        ventanaAgregar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ventanaAgregar.setVisible(true);

        

    }//GEN-LAST:event_btAgregarContactoActionPerformed

    private void btEliminarContacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarContacActionPerformed
        EliminarContacto eliminarcontac = new EliminarContacto();
        eliminarcontac.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        eliminarcontac.setVisible(true);
    }//GEN-LAST:event_btEliminarContacActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btMostrarListaContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarListaContActionPerformed
        ListaContactos lisContact = new ListaContactos();
        lisContact.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lisContact.setVisible(true);
        
        
    }//GEN-LAST:event_btMostrarListaContActionPerformed

    private void btActualizarContacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarContacActionPerformed
        ActualizarContacto actContact = new ActualizarContacto();
        actContact.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        actContact.setVisible(true);
    }//GEN-LAST:event_btActualizarContacActionPerformed
    
    /**
     * Método para mostrar la fecha y hora actual en la interfaz.
     */
    private void mostrarFechaActual() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String fechaActual = dateFormat.format(new Date());
        labfecha.setText(fechaActual); // jLabelFecha es el nombre de tu etiqueta
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizarContac;
    private javax.swing.JButton btAgregarContacto;
    private javax.swing.JButton btEliminarContac;
    private javax.swing.JButton btMostrarListaCont;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labImagenIcon;
    private javax.swing.JLabel labTituloMomento;
    private javax.swing.JLabel labfecha;
    private javax.swing.JPanel panelFondoOpciones;
    private javax.swing.JPanel panelFondoSup;
    private javax.swing.JPanel panleFondoUlt;
    // End of variables declaration//GEN-END:variables
}
